Bootstrap await utility
Saltside/await pull request #1
Opened 2017-01-10 08:00 UTC by siteshJalan

Add await utility with supported tests for init test of
    - http
    - redis
    - mongodb
    - dynamodb
    - thrift

    SRE-5

2017-01-10 09:01 UTC, ahawkins requested changes
Functionally this looks like it will as expected. We can improve the UX though. I suggest we drop the concept for retries and timeouts. Instead we should have a global `-t` (for timeout option) in seconds. This works for the looping structure. Specific command options such as curl opts should be used to handle those cases.

2017-01-10 09:01 UTC, ahawkins commented on bin/await
> +				if mongo --quiet "${host}:${port}/local" --eval 'db.stats()' > /dev/null ; then
I think we should drop the host and port arguments and use `-- [MONGO_OPTS`. This way people can also specify user names, passwords, or whatever other junk is required to connect a general mongo server.

2017-01-10 09:01 UTC, ahawkins commented on bin/await
> +				if curl -s --fail -m "${timeout}" "${host}" > /dev/null; then
We should include `$@` here as well. This will allow people to set headers and whatever other stuff they like.

2017-01-10 09:01 UTC, ahawkins commented on bin/await
> +
You can kill this blank line

2017-01-10 09:01 UTC, ahawkins commented on bin/await
> +	case "$subcommand" in
Please use `${subcommand}`.

2017-01-10 09:01 UTC, ahawkins commented on bin/await
> +			local host port=27017 counter=0 retry=3
Please add a blank line

2017-01-10 09:01 UTC, ahawkins commented on bin/await
> +			local host port=6379 counter=0 retry=3
please add a blank line

2017-01-10 09:01 UTC, ahawkins commented on docker-compose.yml
> +      AWS_ACCESS_KEY_ID : "test"
IMO we should remove these aws key variables and pass them to the test. This way we ensure the command passes `$@` along to `aws`.

2017-01-10 09:03 UTC, ahawkins commented
@siteshJalan can we add memcached as well?

2017-01-13 05:20 UTC, siteshJalan commented on docker-compose.yml
> +      AWS_ACCESS_KEY_ID : "test"
adam these variables need to be present in environment. I cannot find an option in aws-cli where i can pass it directly. Only thing i find is via using profiles. Do you know the options which i can use?

2017-01-13 05:22 UTC, siteshJalan commented
@ahawkins : may i drop `-t` in favour of `$@` using which a caller can specifically pass any timeouts needed. We rather give -r which will be used as retry count? what do you think?

2017-01-16 14:15 UTC, ahawkins commented on test/await_test.bats
> +	run await mysql -h mysql -r 5 -- --user=root --password=secret mydb
These should be environment variables.

2017-01-17 07:08 UTC, siteshJalan commented on test/await_test.bats
> +	run await mysql -h mysql -r 5 -- --user=root --password=secret mydb
though of putting it here so that `$@` could be tested as well.

2017-01-30 06:50 UTC, ahawkins commented
@terlar this may be bikeshedding, but I have a proposal for simplify the UX given you've updated all checks to use URIs. Here's my proposal:

```
$ await [-r RETRY_COUNT] redis://host:port/db -- [ REDIS_CONNECTION_OPTS ]
$ await [-r RETRY_COUNT] mysql://user:password@host:port -- [ MYSQL_CONNECTION_OPTS ]
$ await [-r RETRY_COUNT] memcached://host:port -- [ MEMCACHED_CONNECTION_OPTS]

2017-01-30 09:46 UTC, terlar commented
Yeah, that looks cleaner, I can't come up with any problem doing that at this point.

2017-01-30 22:07 UTC, terlar commented
The only tricky part is with the memcached, I think they use tcp:// prefix? Also dynamodb use http:// as prefix.

2017-01-31 04:12 UTC, ahawkins commented
> The only tricky part is with the memcached, I think they use tcp:// prefix? Also dynamodb use http:// as prefix.

I suggest we use the protocol in the first positional argument to determine the check type (e.g. http, mysql, memcached etc). Then in the handler for the check the type can be replaced with something specific if needed. It depends also on _how_ we do the check for each one. What do you think about this:

- `http(s)://` - curl
- `mongo://` - python script
- `mysql://` - python script
- `dynamodb://` - python script
- `memcached` - python script
- `redis` - python script

Where possible we can just handle the full URI off to a library else we can split it ourselves.

2017-01-31 04:39 UTC, ahawkins commented
@terlar I took a spike on this in https://github.com/Saltside/await/pull/4. Look at all those deletions :D

2017-01-31 10:26 UTC, merged